### ISSUE TITLE
Develop UI using Angular 7+

### ISSUE THREAD

**Issue by viv9k** [ScrumPokerOSS/scrumpokeross#12]
Currently the UI is in basic html, convert the current ui to component driven approach that will help in dividing multiple UI and code reusability.

This can result in solving many problems, in ui as well as ease future development process. 

Issue reference: #11 #8

**Comment by MiguelRodriguezR** [comment]
Is anyone working on this issue already ?

**Comment by viv9k** [comment]
> Is anyone working on this issue already ?



> Is anyone working on this issue already ?

The Issue is nearly implemented, You can take a look at #16

**Comment by viv9k** [comment]
@MiguelRodriguezR Please take a look at #16

**Comment by viv9k** [comment]
@MiguelRodriguezR You can also look upon the following #17
